print ("Hello World")
print ("Hello Again")
print ("I like typing this")
print ("This is so much fun")
print ("Yay, printing")
print ("I'd much rather you 'not'")
print ("I 'said', do not touch this ")
